#Workflow name
name: Master Release Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master

jobs:
  pyinstaller-windows-build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: requirements.txt
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.spec'
          requirements: 'src/requirements.txt'
          options: --icon=./doc/logo.ico,--name "IPC-Installer"
  pyinstaller-linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: requirements.txt
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.spec'
          requirements: 'src/requirements.txt'
          options: --icon=./doc/logo.ico, --name "IPC-Installer"